# Generated by Django 4.2.16 on 2024-10-26 14:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("CollaBand_App", "0002_alter_chat_acceptor"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="creationdate",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
